name: Tesults - Cypress

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3

      - name: Run tests and publish
        uses: actions/setup-node@v3
        env:
          TESULTS_E2E: ${{ secrets.TESULTS_E2E }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: TESULTS_E2E=$TESULTS_E2E npm run e2e:headless:tesults
